[2025-03-13T23:41:27.618+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-13T23:41:27.636+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: open_weather_etl.test_transform manual__2025-03-13T23:37:59.293197+00:00 [queued]>
[2025-03-13T23:41:27.881+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: open_weather_etl.test_transform manual__2025-03-13T23:37:59.293197+00:00 [queued]>
[2025-03-13T23:41:27.881+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 3
[2025-03-13T23:41:27.886+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): test_transform> on 2025-03-13 23:37:59.293197+00:00
[2025-03-13T23:41:27.889+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=344) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-13T23:41:27.892+0000] {standard_task_runner.py:72} INFO - Started process 345 to run task
[2025-03-13T23:41:27.891+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'open_weather_etl', 'test_transform', 'manual__2025-03-13T23:37:59.293197+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpofbiqmyu']
[2025-03-13T23:41:27.893+0000] {standard_task_runner.py:105} INFO - Job 50: Subtask test_transform
[2025-03-13T23:41:27.916+0000] {task_command.py:467} INFO - Running <TaskInstance: open_weather_etl.test_transform manual__2025-03-13T23:37:59.293197+00:00 [running]> on host e9011fd27724
[2025-03-13T23:41:27.957+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='open_weather_etl' AIRFLOW_CTX_TASK_ID='test_transform' AIRFLOW_CTX_EXECUTION_DATE='2025-03-13T23:37:59.293197+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-13T23:37:59.293197+00:00'
[2025-03-13T23:41:27.958+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-13T23:41:27.965+0000] {logging_mixin.py:190} INFO - Rnning test_trasnform task
[2025-03-13T23:41:27.965+0000] {logging_mixin.py:190} INFO - Testing transformation module
[2025-03-13T23:41:27.972+0000] {python.py:240} INFO - Done. Returned value was: Test completed successfully
[2025-03-13T23:41:27.978+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-13T23:41:27.979+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=open_weather_etl, task_id=test_transform, run_id=manual__2025-03-13T23:37:59.293197+00:00, execution_date=20250313T233759, start_date=20250313T234127, end_date=20250313T234127
[2025-03-13T23:41:27.998+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-13T23:41:28.004+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-13T23:41:28.005+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
