[2025-03-14T18:24:37.819+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-14T18:24:37.826+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: open_weather_etl.extract manual__2025-03-14T18:24:37.113603+00:00 [queued]>
[2025-03-14T18:24:37.970+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: open_weather_etl.extract manual__2025-03-14T18:24:37.113603+00:00 [queued]>
[2025-03-14T18:24:37.970+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-14T18:24:37.975+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract> on 2025-03-14 18:24:37.113603+00:00
[2025-03-14T18:24:37.979+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=180) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-14T18:24:37.980+0000] {standard_task_runner.py:72} INFO - Started process 181 to run task
[2025-03-14T18:24:37.980+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'open_weather_etl', 'extract', 'manual__2025-03-14T18:24:37.113603+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/open_weather_dag.py', '--cfg-path', '/tmp/tmp6y1cx08h']
[2025-03-14T18:24:37.981+0000] {standard_task_runner.py:105} INFO - Job 62: Subtask extract
[2025-03-14T18:24:38.000+0000] {task_command.py:467} INFO - Running <TaskInstance: open_weather_etl.extract manual__2025-03-14T18:24:37.113603+00:00 [running]> on host a8e3300004fc
[2025-03-14T18:24:38.029+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='lherrera5034@gmail.com' AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='open_weather_etl' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-03-14T18:24:37.113603+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-14T18:24:37.113603+00:00'
[2025-03-14T18:24:38.029+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-14T18:24:38.039+0000] {logging_mixin.py:190} INFO - host
[2025-03-14T18:24:38.039+0000] {logging_mixin.py:190} INFO - 5432
[2025-03-14T18:24:38.039+0000] {logging_mixin.py:190} INFO - your_username
[2025-03-14T18:24:38.039+0000] {logging_mixin.py:190} INFO - your_password
[2025-03-14T18:24:38.045+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-14T18:24:38.048+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-14T18:24:38.049+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=open_weather_etl, task_id=extract, run_id=manual__2025-03-14T18:24:37.113603+00:00, execution_date=20250314T182437, start_date=20250314T182437, end_date=20250314T182438
[2025-03-14T18:24:38.082+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-14T18:24:38.092+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-14T18:24:38.093+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
